# Generated by Django 2.1.4 on 2020-03-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('capacity', models.IntegerField(default=10)),
                ('tickets_remaining', models.IntegerField(default=10)),
            ],
        ),
    ]
